# Generated by Django 2.0.7 on 2018-07-10 06:26

import django.contrib.auth.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Kullanici',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('TC', models.BigIntegerField(unique=True)),
                ('Kullanıcı_adı', models.CharField(max_length=20, unique=True)),
                ('Ad', models.CharField(max_length=30)),
                ('Soyad', models.CharField(max_length=30)),
                ('is_active', models.BooleanField(default=False)),
                ('is_staff', models.BooleanField(default=False)),
                ('e_Mail', models.EmailField(max_length=255, unique=True)),
                ('Rol', models.CharField(choices=[('Admin', 'Admin'), ('User', 'User')], max_length=50)),
                ('Sifre', models.CharField(max_length=24)),
            ],
            options={
                'abstract': False,
            },
            managers=[
                ('nesne', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Takim',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Ad', models.CharField(max_length=50)),
                ('numara', models.ManyToManyField(to='Ortak.Kullanici')),
            ],
        ),
    ]
