# Generated by Django 2.0.7 on 2018-08-01 06:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bağlantı', '0002_auto_20180801_0948'),
        ('account', '0001_initial'),
        ('Ortak', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Yorum',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('yorum', models.CharField(max_length=255)),
                ('yorum_tarihi', models.DateTimeField(auto_now_add=True)),
                ('baglanti', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='contact_comments', to='bağlantı.Baglanti')),
                ('hesap', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='hesap_yorum', to='account.Hesap')),
            ],
        ),
        migrations.AlterField(
            model_name='kullanici',
            name='Ad',
            field=models.CharField(max_length=30, verbose_name='AD'),
        ),
        migrations.AlterField(
            model_name='kullanici',
            name='Kullanıcı_adı',
            field=models.CharField(max_length=20, unique=True, verbose_name='KULLANICI ADI'),
        ),
        migrations.AlterField(
            model_name='kullanici',
            name='Rol',
            field=models.CharField(choices=[('Admin', 'Admin'), ('User', 'User')], max_length=50, verbose_name='ROL'),
        ),
        migrations.AlterField(
            model_name='kullanici',
            name='Sifre',
            field=models.CharField(max_length=24, verbose_name='ŞİFRE'),
        ),
        migrations.AlterField(
            model_name='kullanici',
            name='Soyad',
            field=models.CharField(max_length=30, verbose_name='SOYAD'),
        ),
        migrations.AlterField(
            model_name='kullanici',
            name='e_Mail',
            field=models.EmailField(max_length=255, unique=True, verbose_name='E-POSTA ADRESİ'),
        ),
        migrations.AddField(
            model_name='yorum',
            name='yorum_kimden',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Ortak.Kullanici'),
        ),
    ]
