# Generated by Django 2.0.7 on 2018-08-01 06:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bağlantı', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='baglanti',
            old_name='tanımlı',
            new_name='assigned_to',
        ),
    ]
